name: Test all actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: opengovsg/action-current-time@master
        id: current-time
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: echo $TIME
